[package]
name = "php-rust-extension"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ext-php-rs = "0.7.4"
serde = "1.0.137"
serde_json = "1.0.81"

[lib]
crate-type = ["cdylib"]
bench = false
